version: '3.4'

services:
  databasecreator:
    image: ${DOCKER_REGISTRY-}databasecreator
    build:
      context: .
      dockerfile: DatabaseCreator/Dockerfile
  vehicleswebapp:
    image: ${DOCKER_REGISTRY-}vehicleswebapp
    build:
      context: .
      dockerfile: VehiclesWebApp/Dockerfile
  vehiclestatusupdater:
    image: ${DOCKER_REGISTRY-}vehiclestatusupdater
    build:
      context: .
      dockerfile: VehicleStatusUpdater/Dockerfile

